name: "Buildwise GitHub action"
description: "Use AI for security and gas optimizations with Buildwise"
inputs:
  github-token:
    description: 'GITHUB_TOKEN'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - shell: bash
      run: |
        git fetch origin main --depth 1
        git diff origin/main > diff
    - shell: bash
      run: |
        cat diff
        curl -X POST -d "$(cat diff)" https://8d33-85-246-66-143.ngrok-free.app > test-out
        cat test-out
    - uses: actions/github-script@v7
      with:
        github-token: ${{inputs.github-token}}
        script: |
          let commits = await github.rest.pulls.listCommits({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          })
          let commit_sha = commits.data[commits.data.length - 1].sha
          github.rest.pulls.createReviewComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            commit_id: commit_sha,
            path: "src/Counter.sol",
            start_line: 5,
            line: 7,
            body: "It is possible to improve the packing of the variables on the 32-bytes slots.\r\n```suggestion\r\n    uint256 public number;\r\n    uint128 public number3;\r\n    uint128 public number2;\r\n```"
          })
