name: "Buildwise GitHub action"
description: "Use AI for security and gas optimizations with Buildwise"
inputs:
  github-token:
    description: 'GITHUB_TOKEN'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - id: git-diff
      run: git diff
    - run: echo ${{ steps.git-diff.outputs.modified }}
    - uses: actions/github-script@v7
      with:
        github-token: ${{inputs.github-token}}
        script: |
          github.rest.issues.listComments({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
          })
    - uses: actions/github-script@v7
      with:
        github-token: ${{inputs.github-token}}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '👋 Thanks for reporting!'
          })
