name: "Buildwise GitHub action"
description: "Use AI for security and gas optimizations with Buildwise"
inputs:
  github-token:
    description: 'GITHUB_TOKEN'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - shell: bash
      run: git diff > diff.txt
    - shell: bash
      run: cat diff.txt
    - uses: actions/github-script@v7
      with:
        github-token: ${{inputs.github-token}}
        script: |
          const fs = require('fs')
          let comms = github.rest.issues.listComments({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
          })
          fs.writeFile('diff2.txt', comms, (err) => {
            if (err) throw err;
          })
    - shell: bash
      run: cat diff2.txt
    - uses: actions/github-script@v7
      with:
        github-token: ${{inputs.github-token}}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '👋 Thanks for reporting!'
          })
