name: "Buildwise GitHub action"
description: "Use AI for security and gas optimizations with Buildwise"
inputs:
  github-token:
    description: 'GITHUB_TOKEN'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - shell: bash
      run: git diff
    - uses: actions/github-script@v7
      with:
        github-token: ${{inputs.github-token}}
        script: |
          const fs = require('fs')
          github.rest.pulls.listReviewComments({
            pull_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
          }).then((data) => fs.writeFile('diff2.txt', JSON.stringify(data), (err) => {
            if (err) throw err;
          }))
    - shell: bash
      run: cat diff2.txt
        # - shell: bash
        #   run: echo "SHA_COMMIT=$(git rev-parse --long HEAD)" >> "$GITHUB_ENV"
    - uses: actions/github-script@v7
      with:
        github-token: ${{inputs.github-token}}
        script: |
          github.rest.pulls.createReviewComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number,
            commit_id: process.env.GITHUB_SHA,
            path: "src/Counter.sol",
            start_line: 5,
            line: 7,
            body: "It is possible to improve the packing of the variables on the 32-bytes slots.\r\n```suggestion\r\n    uint256 public number;\r\n    uint128 public number3;\r\n    uint128 public number2;\r\n```"
          })
